version: '3.8'
services:
    denvergamer:
        container_name: denvergamer
        image: denvergamer:latest
        build:
            context: ./
            dockerfile: ./Dockerfile
        restart: always
    disctogether:
        container_name: disctogether
        image: disctogether:latest
        build:
            context: ./
            dockerfile: ./DiscordTogether/Dockerfile
        restart: always